version: '3'

services:
  ravendb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "38888:38888"
    volumes:
      - ../data:/opt/RavenDB/Server/RavenData